### ISSUE TITLE
Warzone custom item

### ISSUE THREAD

**Issue by DeternoMC** [WarzoneMC/Warzone#100]
In minehut, when connecting to warzone, we should have a custom item like a diamond sword, iron sword or bow or something that'd separate us with all the other servers. This will be easy to see which server is warzone on the list, so you dont have to go through a whole 4-6 lines just to find which one is warzone to join.

If you cant buy it in their store, I believe just asking luuke might do the trick!

**Comment by FieryAU** [comment]
The server is usually on the 1st row the of server list, but it would seem more appealing to the public.

**Comment by JustNoah** [comment]
Well I mean you can just /join warzone so **-1**

**Comment by BennyDoesTheStuff** [comment]
The Warzone server used to have a server icon, but it was removed for some reason. Though it shouldn't be that hard for MatrixTunnel to add it back if he really wanted to.

**Comment by tjhubz** [comment]
It's broken, but we have one.
