### ISSUE TITLE
Weighted Team Join Mechanics

### ISSUE THREAD

**Issue by Palmidence** [WarzoneMC/Warzone#102]
# Weighted Team Join Mechanics
## A preventative measure for team stacking

On Warzone, team-based gameplay is the heart of the server. A lot of people come to Warzone to play fair, balanced, and fun objective oriented matches for everyone to enjoy. However, sometimes Warzone does not provide that consistently, due to something called **team stacking**.

-------------

**What is team stacking?** Team stacking is defined as having numerous players join the same team, usually paired with experienced players, in order to create an unfair advantage against the opposing team. Especially in smaller matches, where team stacking is more damaging, it can almost always guarantee a win for the team that stacks depending on the advantage of players.

**Why is it a problem?** This is not good for new players joining who will always be outmatched by all-star players within Warzone that collectivize into the same team. This is not good for players who try to have a balanced experience with the network: it may spoil the fun and they may not return. This system does not look good for marketing, and furthermore it is not presentable to other people who come from different backgrounds of similar networks.

**How do you suggest fixing it?** I believe there should be an incentive for the developers to control how many donors can pile onto a team to create such an advantage. I believe there should be weighted team joining mechanics.

- Perhaps there could be a certain percentage that we cut users from joining after it has been reached: such as `85% of 20`... which could make teams at maximum stack a 17v20, which is only 3 additional players. 
- We could also disallow team switching after a certain duration in the game, so that the mechanic prevents statistical abuse: that way, it covers the basis for the rule, so we don't ban for it anymore, and so that it makes it fair for when moderators are not online to catch it.
- Sort teams based on stats (https://github.com/WarzoneMC/Warzone/issues/75)

Either way, with weighting players, we should find a way to minimize team stacking to give everyone playing an equal opportunity of enjoyment. 

Feel free to suggest possible preventative measures below.

This is not related to https://github.com/WarzoneMC/Warzone/issues/75, although https://github.com/WarzoneMC/Warzone/issues/75 would be a good addition to this topic.

**Comment by Hxnr** [comment]
#75 offers a better and more simple solution
