### ISSUE TITLE
Paginate maps list

### ISSUE THREAD

**Issue by Palmidence** [WarzoneMC/Warzone#106]
There are so many, you can't navigate through them as easily anymore. There are an upwards of 50 maps soon and splitting them into pages would be the best way to go about it, rather than spam them all in a list.

**Comment by JustNoah** [comment]
#maps on the warzone discord

**Comment by tjhubz** [comment]
He meant the /maps command in game

**Comment by Synconix** [comment]
Isn't there already a /maps

**Comment by Palmidence** [comment]
@Synconix Yes, there is a maps command, but it needs to be broken up into pages.

So, if I were to do `/maps`, it should display as:
- Map 1 by <authors>
- Map 2 by <authors>
- Map 2 by <authors>

**Comment by Synconix** [comment]
Since this is in TO-DO I might try to do it

**Comment by Aerh** [comment]
I've been working on something like this. Still need to see if it works without breaking every so often.
