### ISSUE TITLE
Extra XP for killing someone on leaderboard

### ISSUE THREAD

**Issue by ghost** [WarzoneMC/Warzone#108]
You should make it so you get extra XP when you kill someone on the leaderboard. As I am typing this Unburnable is #1 on the leaderboard so you should make it so if you kill #1 on the leaderboard you get extra XP since that player is on the leaderboard and they are really good it would be a challenge to kill him. And again as I am typing this Klluff is 25 on the leaderboard so you get the least extra XP for killing him.         So if you kill Unburnable you get like 50 extra XP (just an example) and if you kill Klluff you get like 5 extra XP (again just an example)

**Comment by lukechatton** [comment]
This won't be possible until they redo their XP implementation.

**Comment by JustNoah** [comment]
Alright

**Comment by Bearinx** [comment]
I personally don't like this idea, if we were to implement this the leaderboard players would get targeted and would ruin their stats and ruin the gameplay for them.
