### ISSUE TITLE
FFA Gamemode

### ISSUE THREAD

**Issue by Hordesworn** [WarzoneMC/Warzone#114]
I have been coming up with game modes for Warzone maps and I have come up with an FFA game mode.

(Nobody can join after the game has started) Players will be in a not too small arena, or a decently sized map, and will either have a few lives or one life to make the game go quicker. The aim of the game is to be the last person standing, the winner would get a decent amount of XP depending on a number of kills you got. There would also be random loot drops for a piece of armor, a sword, or a golden apple.

If you stay alive for a certain amount of time, all players would get an item / boost, this could be a potion effect (lucky or unlucky), or a golden apple, or even a random piece of gear as an alternative to the loot drops.

I hope this could be considered 👍

**Comment by Palmidence** [comment]
This would be a map request, not a plugin request(?). This is already possible by making different colored teams, unless you are asking for a friendly-fire module. The other features are planned in the future as well.

**Comment by tjhubz** [comment]
There would be an FFA gamemode (everyone for themselves) but you could mix it with blitz to stop respawn.

**Comment by DeternoMC** [comment]
We previously had this when it was the person with the most kills that won. I see no reason in adding it back :)

**Comment by Synconix** [comment]
I was actually going to suggest this, but then I found this post! **+1**
