### ISSUE TITLE
Top Killer on bossbar

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#115]
Maybe the top killer for that round gets put on the bossbar like "Player is the top killer for this round!" and it changes whenever someone else is the top killer. And at the end whoever is the top killer gets extra XP? Idk what that thing is called like you know how people put text above that enderdragon/wither health bossbar thing?

**Comment by Virtualizes** [comment]
Would be cool

**Comment by Synconix** [comment]
Yea maybe like a top 3...but I really like the bossbar idea because I think it would be cool to have...really hope it gets added

**Comment by Whnd** [comment]
how about at the end of the game it says how many kills and deaths u got like it used to be, how many xp u got and who got the most kills

**Comment by tjhubz** [comment]
Bossbar is already used for countdowns. @Whnd I suggest you make a separate issue for that.
