### ISSUE TITLE
/onlinestaff 

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#117]
Maybe there could be a command /onlinestaff so people can see if there are any staff online in case they find a hacker?

**Comment by FieryAU** [comment]
You can easily press TAB and see if a staff member is online, or you can just see if they have joined via 'User has joined the server'

Even if they might be a spectator and you are in-game, you could just DM a staff member on Discord, or report the player via #reports.

**Comment by scorpion808** [comment]
Adding on to what he said^
Hackers will be able to do that command as well letting then to see if there are any only staff members.

**Comment by Whnd** [comment]
lol hackers could just press tab and know if staff are online

**Comment by Palmidence** [comment]
@Whnd @Virtualizes  Staff ranks do not show in tab, and players in-game cannot see spectators. They'd need to run the proposed command, also it's tedious having to know the staff by name, plus not all of them are online in Discord at a given time. A centralized command that outputs a string of staff would be fine.
