### ISSUE TITLE
/skipvote (vote to skip a map)

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#118]
Maybe you could make a command /skipvote to vote to skip a map? And if it gets like 10 votes the map gets skipped....?

**Comment by Virtualizes** [comment]
Sounds like a great feature! I think there should be a system for it where it depends on how many players are on the server.
For example:

5 players on : 3 votes 
8 players on : 5 votes
15 players on : 8 votes
25 players on : 16 votes

**Comment by Synconix** [comment]
Yea that would be cool...so it depends on how many players are on for how many votes it needs to skip

**Comment by scorpion808** [comment]
I don't think this is a good idea because
1, Can definitely be abused
2. If dnot like a map you can always down vote it on discord

**Comment by tjhubz** [comment]
We may add a new next map voting system but for now, vote on maps in discord. And maps with more dislikes than likes will be removed.
