### ISSUE TITLE
XP for blocks shot?

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#119]
So you know how it says how many blocks if you shoot someone? Like "Player has shot player from 30 blocks away" maybe you could make it so how many blocks you should them is how much XP you get? So like if you shoot someone 30 blocks away you get 30 XP or maybe 1/2? So if you shoot someone 30 blocks away you get 15 XP?

**Comment by Virtualizes** [comment]
I enjoy the current system of gaining experience _(wins and kills)_ because it's quite simple.

It'd be quite over the top if players were able to gain experience whilst shooting someone from not a long distance at all.

I don't think this would be added.

**Comment by scorpion808** [comment]
This will cause a lot of kill stealing with bow shots

**Comment by Synconix** [comment]
_**Issue Closed**_
