### ISSUE TITLE
 An automatic unwanted speech prevention system

### ISSUE THREAD

**Issue by dependants** [WarzoneMC/Warzone#121]
# An automatic unwanted speech prevention system

> Since this version of Warzone has released, I have noticed numerous players expressing their feelings in a disrespectful, intolerable, and immature course of action.
It seems to me that these players are being punished rightfully but not fast enough. We do have a Discord text channel strictly for reporting these types of players, although in addition to that I have come up with a solution to try to stop these kinds of players easier and faster.

**Solution** to solve this problem, an individual system will have to be made. Upon sending a message that is unsupported by the rules will automatically be removed from the chat or filtered out using symbols. The player will receive a strike if the player decides to enter the message for another two times; a warning will occur, and finally, the rule-breaker will be punished accordingly judging by the severity of the chat message.

**Why should this be added?** Adding this system to Warzone will support the server a significant amount because the chat can be moderated when a staff member is unable to be online, or receive the report as they may be away from their computer.

While the staff members can focus on appeals, and players using blacklisted modifications, this system will moderate the chat for them. 

**Additional Comments**
Players would be able to suggest words to the filter bypass list which would appear on a public forum or a repository.

If a player says a word that is not on the filter list but is still an offence, the player would be punished manually.

This system can also be useful for monitoring excessive accusations.

**NOTE:** I am not proposing this suggestion to remove swearing as it is allowed, I am mainly on about threats, sexism, racism, controversial messages such as religion or political flame wars, excessive caps lock, advertisement, or unwanted spam

**Comment by Synconix** [comment]
I think this should be added, I see people spamming a lot of racist/offensive things and it gets really annoying.

**Comment by Palmidence** [comment]
This is a good suggestion, however we'd probably build this into a different plugin.

Since swearing is tolerated on Warzone, I can imagine it'd only be used to prevent hate speech and other terms that have no reason to be said, even with context. We can look into using preexisting filtration plugins like [ChatModerator](https://github.com/OvercastNetwork/ChatModerator).

**Comment by Synconix** [comment]
Well yea true, swearing is allowed you just can't direct it towards other players. This is why we have so many moderators, because they are humans that can detect if a player is actually directing it towards another player. Unless a plugin can do that too idk

**Comment by Virtualizes** [comment]
I know swearing is allowed, but I'm talking about excessive profanity and various other disruptions.

Post edited, might be a bit more clear now.

**Comment by tjhubz** [comment]
Since we cannot detect the context of messages (whether it's meant in a mean way, joking, etc) this will not be added. Players can make reports if someone is being toxic. If someone wants to say something and it's blocked, they will figure out a way to say it, whether it's using dashes, numbers, etc.
