### ISSUE TITLE
Auto Broadcast

### ISSUE THREAD

**Issue by ghost** [WarzoneMC/Warzone#122]
Make an auto broadcast that advertises the discord and website, etc.

**Comment by Virtualizes** [comment]
That would be cool because some of the new players should get to know the server more and all get involved with the community, as well as seeing the leaderboards and others statistics.

**Comment by Synconix** [comment]
This would be cool because if this suggestion does get put on the to-do list I could probably code an auto broadcast system.

**Comment by Synconix** [comment]
This would be cool so people can get involved in the community more. Join the discord, view the website and stuff. I hope this gets put into consideration because I would probably be able to code this feature.

**Comment by Synconix** [comment]
**Re-Opened Until Added**
