### ISSUE TITLE
/report command

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#125]
Make a /report command in game, this can be used for if you see a hacker you can /report and it sends to the discord so mods can see it and take care of it, maybe you don't want to open up your discord to report them or your in the middle of a game and need to report them.

**Comment by Virtualizes** [comment]
#reports on Discord is already a thing and another command wouldn't be needed.

**Comment by Synconix** [comment]
Yea but what if someone doesn't have discord? Or is in the middle of a match they can just quickly /report someone

**Comment by scorpion808** [comment]
Or they can actually get discord

**Comment by Synconix** [comment]
_**Issue Closed**_
