### ISSUE TITLE
/suicide command

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#126]
Ya know those times when you fall into the void but don't die, well add /suicide command! Or you can just fix the issue of not dying. This could be useful for other things such as if you fall and you wanna speed up the process of death just use the command, or if you run out of arrows and wanna respawn with new ones, use the suicide command. You may think "well what if someone is hitting you and you just suicide so they can't get the kill" well...just make it so if someone hits you and you do /suicide they get the kill...simple.

**Comment by tjhubz** [comment]
Could be left as a comment in the void issue
