### ISSUE TITLE
Glass break, loose health!

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#127]
Make it so glass is a way of defending your wool and make it so if you break glass you start bleeding and losing health, but if you smash it with an axe or smth it doesn't hurt you.

**Comment by Virtualizes** [comment]
In my opinion, this is not needed,

**Comment by Synconix** [comment]
It could be a way of defending, but...nah...idk

**Comment by tjhubz** [comment]
Has already been suggested, but this could be something you add into maps in the json
