### ISSUE TITLE
Mute command for Staff 

### ISSUE THREAD

**Issue by TBGameeer** [WarzoneMC/Warzone#129]
Simple.

A command that staff can use to mute players either temporarily or permanently.

Why? 
Because I consider that permanently banning for spamming or excessive swearing is unfair. I think just a permanent mute would be more appropiate. I know you can appeal if you are banned for it, but I guess it would just be simpler to stay muted.

**Comment by Palmidence** [comment]
Warzone is entirely a team based server that can rely heavily on communication. If a player breaks rules enough to warrant a permanent ban, then they should realize that the consequence for such a punishment would well... be the ban. A mute would only impede gameplay, and plus at that point they will most likely just take their frustration out in other ways, like teamgriefing.

Also, from a moderation standpoint, what if they need help?

**Comment by DeternoMC** [comment]
I honestly don't think this is should be added into tgm/warzone api. If you'd like to suggest a different punishments plugin, I suggest you should.

**Comment by Synconix** [comment]
Moderators have said this a lot. If someone breaks the rules they just get a ban, simple. If they want they can appeal but I don't think this would be added

**Comment by BennyDoesTheStuff** [comment]
Added.
