### ISSUE TITLE
Only bans appeal

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#130]
Make it so only if you are banned you can talk in the appeal channel (and mods of course) maybe you could like make the warzone bot check if you are banned. This is because a lot of people talk in #appeals when they are not supposed to and it gets annoying.

**Comment by Palmidence** [comment]
This can only be done if you link your Discord with your in-game account, however I'm not sure if banned players can register their in-game account with their Discord.

**Comment by Synconix** [comment]
Maybe they could connect it to the server and someone types in their name and it checks if they are banned so they can appeal

**Comment by Synconix** [comment]
**Closed**
