### ISSUE TITLE
Bows can break wool?

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#131]
Make it so that if you shoot wool it breaks...this is because I see A LOT of people not defending and it would make it better so people will actually TRY to defend, maybe you can make it so there is a 30-60 second time limit before you can start shooting to give people time to place defense and stuff.

**Comment by Bearinx** [comment]
In my opinion, this is not that good of an idea, it would lead to the games ending too fast and not making it fun.

**Comment by Synconix** [comment]
That's the thing because it would encourage people to defend more because I barely ever see people defending, some people do but most people don't. I don't know maybe this is not a good suggestion, just my opinion.

**Comment by Virtualizes** [comment]
I mean, I know what I would do if this were to be added. Quickly onestack, find their wool, and sit there and shoot it until I win.

Overall, this is unfair.

**Comment by Synconix** [comment]
_**Post Closed**_
