### ISSUE TITLE
AFK Timeout

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#132]
Maybe you could add like an AFK timeout? Because I once sat in warzone for like 10 hours because I forgot to log off when I went to bed. Maybe this won't be a MAIN priority but it could be a cool side thing too add on.

**Comment by Palmidence** [comment]
Any reason why?

**Comment by Synconix** [comment]
I mean it could just be a side thing to add like I said, maybe so my computer doesn't overheat and explode. Idk lol

**Comment by Synconix** [comment]
**_Closed_**
