### ISSUE TITLE
Notification when entry

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#133]
Make it so if someone enters your wool it notifies you like "SOMEONE HAS ENTERED YOUR WOOL" for like DTW or CTW.

**Comment by Virtualizes** [comment]
CTW already has a notification for picking up a wool.

In DTW, adding a notification like this will probably relinquish the fun of the game.

**Comment by Palmidence** [comment]
We already spam chat when someone breaks a bunch of wools, as well as with the fireworks, so you should be aware that they're there. It shouldn't be the plugin's responsibility to tell you who is at your wool. This is also already a feature when someone picks up a wool.

**Comment by Synconix** [comment]
_**True, post closed**_

**Comment by Synconix** [comment]
_**That is true, post closed**_
