### ISSUE TITLE
Power-Ups/Boosters

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#134]
You should make random powerups around the map. Maybe like 20-second speed or 5-second invisibility.  This would be a cool thing to add to make the game more fun. Or maybe you could add launchpads around the map that launch you into the air.

**Comment by Palmidence** [comment]
No, that makes maps more unbalanced. It would be harder to push the enemy out of locations, if they have invisibility/regeneration/speed/etc. when we're trying to create a fair gameplay environment. We also already offer launch pads in maps like Outbreak and Urban Jungle, however they use command blocks and haven't been thrown into the mix too much as of now.

**Comment by Synconix** [comment]
It's not like they would have all of the abilities at once. They just get like a boost like of speed for 10 seconds at a time. Nothing much, could be cool.

**Comment by Palmidence** [comment]
I know, it's still too much.

**Comment by Virtualizes** [comment]
Warzone is for skill and fun combat, abilities and powerups would be extremely unfair. 

The current style is very good.

**Comment by Synconix** [comment]
True
