### ISSUE TITLE
Appeal/Report On Website?

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#135]
Maybe you could add the appeal and report section to the website so people can do it on the website instead of having it on the discord. This is because people type non-appeal/report related things in the channels and this could be a cool thing to prevent that and also be cool.

**Comment by Virtualizes** [comment]
Teejers or MatrixTunnel already informed a lot of people that the appeals and reports are going to stick to Discord, they are still working on a new way of submitting reports and appeals.

By the way, this issue should have been opened on WarzoneMC/Website repository.

**Comment by Synconix** [comment]
mk
