### ISSUE TITLE
Spawn Kill

### ISSUE THREAD

**Issue by Arkrus** [WarzoneMC/Warzone#136]
On Bridges, Nightsent's new map, breaking a few blocks under a team's spawn will cause infinite spawnkills into the void until someone places a block underneath the spawn. Under the top layer should be bedrock, or have the spawnblock itself be bedrock

**Comment by Virtualizes** [comment]
+1

**Comment by Synconix** [comment]
_**+1**_

**Comment by JapaneseSquid** [comment]
+1

**Comment by BennyDoesTheStuff** [comment]
Issues like this should be added to the [Maps](https://github.com/WarzoneMC/Maps) repo. Closing
