### ISSUE TITLE
Effects on wool break

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#146]
> Description not provided, title says it all

**Comment by Arkrus** [comment]
Uh no. Stalls games way longer, and unnecessary.

**Comment by Synconix** [comment]
Maybe another effect like blindness? Or maybe smth that speeds it up like speed?

**Comment by Arkrus** [comment]
Also unnecessary. It's completely fine as it is.

**Comment by Synconix** [comment]
**_Closed_**
