### ISSUE TITLE
Golden Drought & Potions

### ISSUE THREAD

**Issue by Arkrus** [WarzoneMC/Warzone#147]
At each wool area on Golden Drought, there are potions with 4 negative effects, something like blindness, potion, and nausea. These potions can be used for team griefing. Potion effects should not apply to teammates.

**Comment by tjhubz** [comment]
Update name to “Splash potion affects should not effect teammates”

**Comment by Synconix** [comment]
**+1**

**Comment by BennyDoesTheStuff** [comment]
For changes like this, you would be better off making an issue on the Maps repo. https://github.com/WarzoneMC/Maps
