### ISSUE TITLE
/chat team + /chat all

### ISSUE THREAD

**Issue by ghost** [WarzoneMC/Warzone#149]
If you use this command it will send all your messages to team chat without having to do /t and you can change it back by /chat all

**Comment by Virtualizes** [comment]
How about;?

@ [message] - Executes a message strictly for your team.
/t - Enables team chat so when you type a message it only goes to your team until you disable it using the following command
/g - Enable global chat

**Comment by Synconix** [comment]
Yea do that

**Comment by DeternoMC** [comment]
They're adding a new team system (clans) soon. Maybe wait for that first.

**Comment by JapaneseSquid** [comment]
Is typing 2 letters in front of a message that hard to message your team? Besides, with a toggle sometimes people don’t remember which one they’re typing in (I know from experience) so having to use /t reminds the person what chat they’re typing in. Can someone just close this please

**Comment by BennyDoesTheStuff** [comment]
Adding onto this, also adding a /chat staff for staff members to toggle into the staff chat would be pretty cool too, though you would have to make sure only staff members can toggle staff chat on.
