### ISSUE TITLE
Rank System

### ISSUE THREAD

**Issue by lukechatton** [WarzoneMC/Warzone#153]
It's time for an API centralized rank system!

Goals for the implementation are the following:

1. Rank definitions stored in mongo. Allows for dynamically creating and managing rank definitions (prefixes, permissions, etc) from a web panel or via ingame commands.
2. Ranks used for both minecraft server permissions and website permissions.
3. Multiple rank assignments per player.

**Comment by lukechatton** [comment]
I've started on the node API implementation, but haven't touched anything in the java codebase yet.

If anyone wants to help write some java, we need a model that matches the [MinecraftRank ](https://github.com/WarzoneMC/API/blob/ranks/models/minecraft.js#L41)I wrote in the node api.

**Comment by lukechatton** [comment]
Just checked out https://github.com/WarzoneMC/Warzone/tree/ranks by @jorgeberrex

The rank model looks perfect. But I don't think we will actually need the Rank Manager class. The API will respond with a list of Rank models in the field `ranksLoaded`. 

So we could just add the following to the Player Model:

```java
List<Rank> ranksLoaded;
```

**Comment by lukechatton** [comment]
I think really the only time we will need to retrieve the full rank list from the API is for a `/rank list` command (or something similar) that shows admins what ranks are available to assign users to.

**Comment by jorgeberrex** [comment]
I wasn't aware that the API would respond with the entire rank models; I was guessing it would just return the rank ID, just like it does on `/mc/player/Player`. I'll work on the changes regarding that once I get the opportunity.

**Comment by lukechatton** [comment]
Sweet.

Yeah I figured it would be easiest just to return the full rank object instead of trying to maintain a synced list of ranks in the plugin and assigning them on join via matching id's.

**Comment by lukechatton** [comment]
Should we setup commands that let server operators setup ranks? I guess the endpoints we would need are 

1. `POST /mc/rank` adds a new rank.
2. `POST /mc/rank/:id/prefix` updates a rank's prefix.
3. `POST /mc/rank/:id/permission` adds a permission string to rank permission list.
4. `POST /mc/rank/:id/remove_permission` removes a permission string to rank permission list.
5. `POST /mc/rank/:id/remove` removes a rank.

**Comment by jorgeberrex** [comment]
Ranks should have a `priority` field to make a reliable hierarchy system and not depend on the order the ranks were created/added.

**Comment by jellz** [comment]
@lukechatton do you still work on this lol

**Comment by BennyDoesTheStuff** [comment]
Rank system finished! #233
