### ISSUE TITLE
Kicked for flying glitch on death

### ISSUE THREAD

**Issue by ghost** [WarzoneMC/Warzone#154]
Whenever I die I am kicked for flying...like it literally happens so often, whenever I fall into void or die there is like a 70% chance I will be kicked for flying.

**Comment by DeternoMC** [comment]
Could you record a video on it happening so we can see?

**Comment by Synconix** [comment]
**Issue Solved**

**Comment by Synconix** [comment]
OK, so I thought this was fixed but it is still doing it...

**Comment by tjhubz** [comment]
This happens when your connection to the server is poor.
