### ISSUE TITLE
Separate World For Tournaments

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#156]
Make a separate world/private server for tournaments so people who are not in the tournaments can play separately if that is even possible.

**Comment by BennyDoesTheStuff** [comment]
Possibility, but I don't think an issue is needed just to say something like this. Having a different server for the tournament isn't really a thing that needs to be added to the plugin.

**Comment by lukechatton** [comment]
@MatrixTunnel was looking into creating a bungeecord network inside of Minehut's bungeecord. Apparently he did it a while ago when Minehut was offering third party servers. Not sure if it's still possible though.

**Comment by Synconix** [comment]
Matrix is not admin anymore though XD

**Comment by DeternoMC** [comment]
@Synconix This was 2 hours ago, and we're all aware of it.

@lukechatton "Not sure if it's still possible though." you made minehut, how do you not know if it's possible, I mean you guys could test it.
