### ISSUE TITLE
Block Clear @ 5 Minutes

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#157]
Make it so every like 5 minutes it clears all placed blocks, idk how you would do this without clearing bridges but like whenever I am playing the game people place so many random blocks it just gets in the way and its hard to play.

**Comment by Palmidence** [comment]
No

**Comment by Synconix** [comment]
Or at least make something that fixes the issue with a bunch of scattered blocks.

**Comment by Bearinx** [comment]
It's not an issue its a part of the gameplay, this just ruins the game.

**Comment by Synconix** [comment]
ok then

**Comment by Virtualizes** [comment]
l
