### ISSUE TITLE
/streak command

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#158]
Pretty simple explanation, check your current kill streak, even if it is under 5

**Comment by Virtualizes** [comment]
Perhaps the scoreboard would flicker every so often between round statistics including your current killstreak and highest killstreak in the round.

**Comment by jorgeberrex** [comment]
In my opinion, such small features do not deserve their own independent command. Rotating between the game objective and round statistics on the scoreboard wouldn't be the best option either. I feel like the game objective should be visible at all times as being able to track your current score is always crucial for an effective strategic game-play. I'm pretty sure there are many different approaches that would benefit the development of the game in the long run; perhaps a new entire settings system with an option to display live kill streak in the action-bar and many other settings.

**Comment by Synconix** [comment]
Ok so maybe it could just be in your stats so "Current Streak: 0" or if your not in a game "Current Streak: Not Currently In-Game"

**Comment by DeternoMC** [comment]
No need, but we can add best streak under stats. Your current streak is easy to find out, continue getting more kills and it might pop up with another message in chat "<player> is on a 10 kill streak" etc. Then you will but up to date with your streak. Why do you need to even know your current streak anyways? I'm positive you know how to count.
