### ISSUE TITLE
Chance of missing when shooting a bow

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#164]
**Chance of missing when shooting a bow**

> Make it so whenever you shoot a bow you have like a 25% or 50% chance of missing the person, this could be another way of preventing bow spam and I think it would be really cool

**_-Synconix_**

**Comment by HazryG** [comment]
It would prevent bow spam but would be really annoying; if you just wanted to shoot someone once off of a bridge (say they were just about to rush your wool and no-one could run there in time) and the shot missed, it would change the entire game around and make the game randomised, making it unfair.

**Comment by Palmidence** [comment]
No, this is a PvP game. You can't have chance determine who dies.

**Comment by Synconix** [comment]
k
