### ISSUE TITLE
HP Notifications

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#166]
**HP Notifications**

> Add HP Notifications, so like if you do damage to a player it notifies you how much HP they are at. You may be thinking "This would just cause spam" but you could make it so that if you hit a player twice within a couple seconds (so like if your comboing a player) it doesn't notify you to prevent the spam. Or maybe you could toggle it on and off like /hpnotify on/off

**Comment by HazryG** [comment]
For real, calm down on the constant suggestions. You make so many of these in a space of a day that I don't know what to even think anymore.

**Comment by Synconix** [comment]
nah m8 lol

no but really I will try to calm down on them, just whenever I have a cool idea I will put it, besides I only have made like 2 today lol

**Comment by HazryG** [comment]
SPACE OF A WEEK***

**Comment by Synconix** [comment]
lel

**Comment by scorpion808** [comment]
This isn't pot pvp. And this would cause targeting.

**Comment by Palmidence** [comment]
No.
