### ISSUE TITLE
Players not appearing on tab.

### ISSUE THREAD

**Issue by HazryG** [WarzoneMC/Warzone#169]
Pretty self explanatory :^)

**Comment by DeternoMC** [comment]
They cannot see the players in-game either. The fix to this is just relogging.

**Comment by lukechatton** [comment]
Just to confirm, you aren't talking about not being able to see spectators in tab while on a team right?

**Comment by HazryG** [comment]
No, I was a spectator watching a game and couldn't see a player on a team in the game or on tab. Pretty sure it links in with that other invisible person bug from before.

**Comment by tjhubz** [comment]
Let me know if this is still an issue, pretty sure it's fixed now.
