### ISSUE TITLE
Team switching/Stats abuse

### ISSUE THREAD

**Issue by scorpion808** [WarzoneMC/Warzone#171]
Make it so when someone switches teams it tells everyone in chat. For example: "Player" has switched teams.
I think this should be added so stats abusers can be reported if they get caught doing this when a wool is captured or destroyed. When you comment below just put **+1** or **-1** and why you chose that.

**Comment by Synconix** [comment]
Maybe it doesn't need to tell everyone maybe just staff so if someone switches teams when someone is about to destroy the monument they can be punished.

**Comment by BennyDoesTheStuff** [comment]
This is not really needed. In the future, the better thing to do instead of just announcing a person's name in chat is to move what team non-donors are on if the teams get way too stacked.

**Comment by DeternoMC** [comment]
@BennyDoesTheStuff this is meant for people avoiding a loss/trying to win all games. Switching teams before they loose or an opposing team wins.

I agree, should be added.

**Comment by scorpion808** [comment]
You can always leave the game and join back to switch team

**Comment by LewisP2018** [comment]
@scorpion808, That's why Warzone needs more active staff to keep a eye on this issue.
