### ISSUE TITLE
Vote for extras

### ISSUE THREAD

**Issue by Synconix** [WarzoneMC/Warzone#174]
**Vote for extras**

> Maybe you could be able to vote for extra game modes like infected? Maybe like /gmvote (Game Mode). So like if it gets like 10 votes it sets it to the next map. This could be used so players don't go "OMG DO INFECTED PLSSS OMRGFGS PLSESGR OMFGGGGG PLSSS"

**Comment by Pndq** [comment]
Infected is mainly a event game with a lot of players. However, I can see this being used as a wat to vote on the next map. But, some of the less popular maps that are really well made won't get a lot of time. I think instead of using it to chose the next gamemode, it could be used to vote on a the next map.

**Comment by Synconix** [comment]
> An event game with lots of players

Exactly, lots of players. That is why it would need 10 players to vote in order to start

**Comment by Pndq** [comment]
That is true but say only 10 players are on and they all want to play infected. They vote for it and start to play. 1. It wouldnt be that fun and 2. I think one of the reasons thay Infected is so loved and is special is that its only really played with about 20+ players. Implementing this would ruin that

**Comment by Palmidence** [comment]
No thanks. If it selects a random map based on gamemode, then it can set broken and/or bad ones. It also can be abused. We should just keep it to events.

By the way, infection isn't in the rots for reasons. We shouldn't let players set it outside of events. If a mod is on, just ask. We don't need an entirely new system.
