### ISSUE TITLE
Kill Counter Removal 

### ISSUE THREAD

**Issue by Bearinx** [WarzoneMC/Warzone#177]
Make it so Blitz maps don't count towards a player's stats.

**Comment by BennyDoesTheStuff** [comment]
Instead of just removing player deaths/kills from Blitz maps, it should be a module people can use to disable/enable stats per map inside of the JSON.

**Comment by Bearinx** [comment]
I don't know if you mean a command people can type so people can turn it off or something you can do to the JSON so no kills or deaths count so please specify.

**Comment by BennyDoesTheStuff** [comment]
"people can use to disable/enable stats per map **inside of the JSON**."

**Comment by Bearinx** [comment]
Okay well if this was added it should only be able to be changed in the Blitz maps JSONs

**Comment by Palmidence** [comment]
@Bearinx TGM is meant to be flexible, and offers the option. It should still be possible to do it, not necessarily that it wouldn't arbitrarily be disallowed (we can make a rule against mapmakers adding it for their rotation maps.)

**Comment by BennyDoesTheStuff** [comment]
Added, you can now define this per JSON.
