### ISSUE TITLE
Shears

### ISSUE THREAD

**Issue by scorpion808** [WarzoneMC/Warzone#179]
Shears needs to get removed. Why? Well, it is unfair how you break the wool a lot faster than usual. The team won't have the chance to get to their wool so they can protect it.

**Comment by Palmidence** [comment]
The mapmaker can choose whether or not they want shears on their map.

**Comment by scorpion808** [comment]
No, it should be banned on all maps.

**Comment by DeternoMC** [comment]
@scorpion808 In the end, it's up to the map maker. Now, pretty much everything is decided on what the map maker wants to add. Perhaps, block the crafting of shears instead. If the map maker wants the players to get a shear, they'll need to put it somewhere where it can be stored, example a chest, shulker, furnace, hopper, dropper etc.

**Comment by Synconix** [comment]
Maybe it could be banned on the maps that actually have iron in them, like some maps don't have iron so it's impossible to have shears but in the maps that do, I think they should be banned. 👍

**Comment by tjhubz** [comment]
Again, it’s up to the map creator. Though a module for not being able to craft things would be nice.
