### ISSUE TITLE
Blue team auto-win when the game ends on a tie.

### ISSUE THREAD

**Issue by HazryG** [WarzoneMC/Warzone#18]

**Comment by TheRealPear** [comment]
What kind of glitch is this?

**Comment by Draem** [comment]
it's a glitch that makes blue team automatically wins if the game is a tie. pretty self explanatory based on the title of this issue.

**Comment by BennyDoesTheStuff** [comment]
I think this issue could be closed as it's hopefully will be worked on in the short future based on when it;s completed. #75

**Comment by BennyDoesTheStuff** [comment]
Fixed 👍
