### ISSUE TITLE
OITQ / OITC Gamemode

### ISSUE THREAD

**Issue by DeternoMC** [WarzoneMC/Warzone#181]
If anyone is unaware what OITQ / OITC is, it's pronounced 'One in the quiver' or 'One in the chamber'. This is a minigame where everyone has 1 bow, 1 arrow, and a sword. It's playable on any map, preferably infection maps. Whenever somebody kills someone, they get 1 arrow. Whenever someone shoots someone, its one shot one kill. However, fighting with swords is not one shot 1 kill. That's pretty self explanatory, it's ffa as well. The gamemode is first to a number of kills, which I'm not going to set, but I'd say 25

Example:

Player 1 shoots player 2:
    Player 2 dies. (player 1 looses 1 arrow, then gains 1 back)
Player 2 respawns, misses shot on player 1:
    Player 1 survives, (player 2 has 0 arrows)
Player 3 kills Player 1 and Player 2:
    Player 3 now has 3 arrows (+2 because of the two kills, and he hasnt used any)

etc.

**Comment by Virtualizes** [comment]
Additionally, I have got a few ideas.

- When a player dies, there is a small cool down before respawning, 
- Depending on how big the map is and how much players are online, there would be an an automatic sorter for the kills, or the map creators would simply choose the kill count they desire.
- Perhaps after a certain amount of deaths, the person would be eliminated from the match. 

In conclusion, I suggest this to be added 👍

**Comment by DeternoMC** [comment]
@Virtualizes with your ideas:

1. That could be an addition.

2. If possible, an automatic sorter depending on how many currently online people

3. I don't agree; everyone should be able to win; just trying to keep the traditional oitq feel.

**Comment by tjhubz** [comment]
Instead of creating specific gamemodes, a general gamemode like “Deathmatch” would be created, and then the gamemode could be turned into OITC using the JSON from there. We want to be as general as possible overall, leaving all the tiny details you guys want up to the map creator.
