### ISSUE TITLE
Killstreak of "null"

### ISSUE THREAD

**Issue by AtditC** [WarzoneMC/Warzone#204]
This message appeared after someone killed me, just when I got my 10th kill in a kill streak. (I died right after the kill)

![image](https://user-images.githubusercontent.com/7355350/33186175-da75579e-d087-11e7-91e2-a4a0a1b72da6.png)

**Comment by JapaneseSquid** [comment]
It happens when you kill yourself while having a streak. Doesn’t seem to recognize the void as an entity capable of ending the streak.
