### ISSUE TITLE
Level balancing

### ISSUE THREAD

**Issue by jorgeberrex** [WarzoneMC/Warzone#206]
Currently, the level system is pretty unbalanced since it benefits mostly players that focus on wool/monument breaking. The XP per stat should be balanced so it benefits all players.

Stat | Current | Balanced
--- | ---- | ---
Kill | 1 | 2
Win | 10 | 10
Loss | 5 | 5
Monument Break | 7 | 3

This action might reduce the current level for some players that focus primarily on wool/monument breaking, as well as it might increase the level for players that focus on any other aspects of the game.

This issue is created to receive opinions and feedback from the community.

**Comment by JapaneseSquid** [comment]
Lots of feedback I see.
Anyways make kills like 3 XP please. 
Thanks.
