### ISSUE TITLE
Add support for Vault chat

### ISSUE THREAD

**Issue by TheRealPear** [WarzoneMC/Warzone#207]
Using permission plugin such as PermissionEX or LuckPerm with vault installed doesn't make the chat play nicely with the group prefixes.

**Comment by BennyDoesTheStuff** [comment]
Hopefully, when #153 is completed TGM itself would have a whole permissions and ranks system that needing Vault or PermissionsEx wouldn't be needed. Adding support for Vault currently isn't going to be a thing we will work on.

**Comment by TheRealPear** [comment]
oh well
