### ISSUE TITLE
IP Lookup

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [WarzoneMC/Warzone#227]
Add a /lookup command to lookup all accounts that have joined on an IP.

**Possible usage:**
/lookup <player/IP> Shows all accounts that have joined with the same IP. Lets you hover over each account to quickly see if it's currently punished and the last time that account has joined the server.

**Comment by jellz** [comment]
The IPs themselves should only be shown to staff members Senior Mod+ though.

**Comment by D7F** [comment]
good idea actually, jorge should add this, but i dont like the idea with the ip thing, i only prefer the player one.

**Comment by BennyDoesTheStuff** [comment]
I don't see a reason why the "IP" lookup would be a bad idea. Can you explain your reasoning a bit more? It's mainly so if a staff member is interested in seeing if a certain IP address has multiple accounts linked to it. There are other ways staff members can get a player's IP, so not adding it wouldn't block the player's IP if that's what you want to be prevented.

**Comment by Virtualizes** [comment]
I reckon this would be a great utility for a staff member, I have used an IP Lookup program on various other servers and it seems to work great and effective.

**Comment by D7F** [comment]
@BennyDoesTheStuff maybe, a staff member is a abusing one and none ever knew it and that staff member abuses it and DDOS'es all the players, thats my reason.

**Comment by Aerh** [comment]
@D7F It's up to the people who select these staff members to find out this information as to if they will abuse the powers given to them. A utility like this is very useful to catching alternate accounts and seeing if a player is using any other accounts on the server, e.g. for boosting etc.

**Comment by TheRealPear** [comment]
@D7F if a staff member is making all that effort to DDOS every single player, then I applaud him.

**Comment by Sniped** [comment]
@D7F you do know that DDOSing is a [10 year sentence](https://legalpiracy.wordpress.com/2011/01/10/ddos-attacks-and-the-law/) in prison, right? Not even a demoted staff member would dare attempt to DDOS every player the punishment system has record for. The staff team is trusted greatly upon the community and none of us have an intention to "DDOS" a player, let alone every single one.

**Comment by jellz** [comment]
@Sniped That might just be in one specific state or country, you can't really say that expecting it to be valid in all the countries a player could be playing from; also, @BennyDoesTheStuff @D7F couldn't the command just show the alt accounts but not display the actual IP address to the player? Concept attached to this comment.
![image](https://user-images.githubusercontent.com/24366082/36581391-cb920e3a-18c0-11e8-843a-8ded69068954.png)

**Comment by BennyDoesTheStuff** [comment]
The player's IP doesn't really matter since even if the IP is hidden, staff members can see a person's IP inside of the punishments if they use /p <player>

**Comment by Sniped** [comment]
@jellz It is within many countries and states that this law is in act. The possibilities that a player is playing from an area that this law is pardoned is slim. Even if a staff member or player was doing such, they would be blacklisted from the Minehut network and any chance of these people building up their reputation with a community is also pretty slim.

**Comment by jellz** [comment]
@Sniped How would they even know who issued the DDoS?
@BennyDoesTheStuff Ah, okay, so it's settled then.

**Comment by Sniped** [comment]
@jellz That just goes down to police investigation. In theory, they can just trace the mass connections back.

**Comment by jellz** [comment]
@Sniped I know this is going completely off-topic to the issue, so if you'd like to further discuss this contact me on Discord.

**Comment by JapaneseSquid** [comment]
Well, I don’t want any accusations of turning warzone into Avicus, but I’m Avicus there was a staff bot with the command !altcheck, and only senior mods can actually see the Ip

**Comment by JapaneseSquid** [comment]
A discord bot, that is
