### ISSUE TITLE
Clean chat.

### ISSUE THREAD

**Issue by D7F** [WarzoneMC/Warzone#230]
This command is ONLY for staff, and is used when there is some very bad word, such as someone spamming the word (NIGGER PUSSY) <--- that actually did happen once. And then, one of the staff members can clean chat so the other people wont have to see it.

**Comment by tjhubz** [comment]
There’s no need to say the actual explitive.

**Comment by jellz** [comment]
lmao, agree with @tjhubz 

also, _expletive*_

**Comment by BennyDoesTheStuff** [comment]
Duplicate of #124
