### ISSUE TITLE
Empty map and rotation pages

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [WarzoneMC/Warzone#236]
When using /maps to view all the maps, depending on the number of maps, the server will show 1 or sometimes 2 extra pages with no maps listed on them
![Maps](https://i.imgur.com/7WXfK6w.png)

**Comment by tjhubz** [comment]
@Subtract

**Comment by draeeeeeeeeeeeem** [comment]
ill fix for unban from wz discord
