### ISSUE TITLE
Feature in map json to disable stat tracking

### ISSUE THREAD

**Issue by tjhubz** [WarzoneMC/Warzone#237]
In the json of a map, there should be a feature that disables stat tracking on that specific map. This would be useful for minigame maps that involve unbalanced sides/ a lot of deaths, etc.

It should be set to track stats by default (so old map json should not have to be changed).

**Comment by jorgeberrex** [comment]
Structure:
```JSON
"stats": {
     "disable": false,
     "notifydisable": true,
     "showlevel": true
 }
```
