### ISSUE TITLE
Add /nh or similar command for namehistory

### ISSUE THREAD

**Issue by AtditC** [WarzoneMC/Warzone#241]
This could be a VIP+ feature.

Example:
/nh TokyoSquid would return:
Squidvicus (2 months ago)
ChristmasSquid (3 months ago)
JapaneseSquid (4 months ago)

etc.

**Comment by jellz** [comment]
There's literally forge mods that add this command. 5zig, LabyMod, Vanilla Enhancements, etc.

**Comment by AtditC** [comment]
Ye but it would make a great feature for donator ranks, so they don't have to download a mod just to see namehistories ingame.

**Comment by JapaneseSquid** [comment]
I find it more of a pain to use laby mod than when I used /nh back in the Avicus days, but that’s just me, besides nh also shows when the player first joined the server

**Comment by pdxryanpdx** [comment]
^

**Comment by jellz** [comment]
Why would they make **/nh** a Donator perk if they did infact add the command? You could literally use a mod, a Discord bot, the Mojang API, NameMC, so many alternatives - and if they did decide to add this command, it should not be a donator perk. Something they could do though, is add the name history to **/stats**.

**Comment by jellz** [comment]
Why would you need someone's name history in the first place? haha

**Comment by pdxryanpdx** [comment]
I don't know. This wasn't my idea...... xd

**Comment by JapaneseSquid** [comment]
Because people change their names and if you want to know who they are it’s useful 
Also, donor perks are pretty dry right now so it can help a bit 
It’s a small feature that I’m sure can be done with not too much effort

**Comment by pdxryanpdx** [comment]
All ViP does is let’s you pick our team

**Comment by AtditC** [comment]
We need /nh to check name histories of players without switching to the browser and typing namemc.com etc. It's way more comfortable to just do it in-game. Why would I want to download a whole new mod only to see name histories? That's way too much effort.

**Comment by Trophonix** [comment]
TGM is a pvp suite, not a moderator toolkit.

**Comment by danielgulic** [comment]
Yet it has its own punishment commands
