### ISSUE TITLE
Teleport Tool not working

### ISSUE THREAD

**Issue by Cooperinthedirt** [WarzoneMC/Warzone#25]
In teamGG, the Teleport Tool doesn't do anything. Thought I would bring this up to get fixed.

**Comment by Draem** [comment]
Only ops can use the teleport tool because it's just using WorldEdit's teleport tool, which only ops can use.
I did a quick search and there isn't a permission node for it. So unless someone codes this into Team.GG, it won't work.

**Comment by lukechatton** [comment]
There is a permission node for it. We did this back in the previous iteration of warzone. I'l look it up later.

**Comment by xaoseric** [comment]
worldedit.navigation.jumpto.command
worldedit.navigation.thru.command

Those might be the permission nodes your looking for
