### ISSUE TITLE
Afk players in game

### ISSUE THREAD

**Issue by ghost** [WarzoneMC/Warzone#253]
Afk players in the game take up space and can unbalance teams. After being afk for a while, players should be moved to spectators automatically

*This issue was submitted through our bug reporting tool.*

**Comment by pdxryanpdx** [comment]
Sometimes players have to go or something but this is an good idea. Maybe 5 mins of afk time then kicked?

**Comment by LewisP2018** [comment]
Good idea! I am annoyed how many people I see AFK. 5 minute timer is needed.

**Comment by Nuggets1** [comment]
This seriously needs to be added!
