### ISSUE TITLE
Wool chest is breakable on CTW

### ISSUE THREAD

**Issue by TheRealPear** [WarzoneMC/Warzone#254]
I'd record a video of this, but I'd rather not get into trouble. 

Basically, breaking the chest in the wool base on any Capture the Wool map makes the game impossible to win. I haven't seen much people abusing this, but I'd rather have this fixed asap.

**Comment by pdxryanpdx** [comment]
If you want I will record when nobody is on

**Comment by TheRealPear** [comment]
@pdxryanpdx Amazingly fast reply, feel free to do so

**Comment by MatrixTunnel** [comment]
I'll try fixing this later tonight

**Comment by pdxryanpdx** [comment]
Some people were on when I did this but I replaced the chest

**Comment by pdxryanpdx** [comment]
https://youtu.be/wcUJ-kCn3Mo

**Comment by TheRealPear** [comment]
@pdxryanpdx after watching your video, you couldn't break the first wool chest but you can break the second chest.

I'm guessing this feature is already half-implemented.

**Comment by pdxryanpdx** [comment]
Might be a problem with the JSON

**Comment by danielgulic** [comment]
Tested this locally on several CTW maps. The problem only occurred on the Cargo map, which is the one in the video. This is a map JSON problem and this issue must be marked as invalid and closed.
