### ISSUE TITLE
Default users don't have permission for the `/discord unlink` command

### ISSUE THREAD

**Issue by D7FAlt** [WarzoneMC/Warzone#257]
/discord unlink does not work plz halplppppppp,

reason im saying this: because i am a old time player and ive changed my name.. now i cannot talk in server-chat and i cannot do /discord unlink plz halpp

**Comment by MatrixTunnel** [comment]
@jorgeberrex removed default ranks from Warzone which causes this issue. I'll look into fixing later today

**Comment by jorgeberrex** [comment]
This has actually been an issue even before the release of the built-in ranks system

**Comment by D7FAlt** [comment]
SoOOoO CaN YoU FiX ThAt?





xd

**Comment by tjhubz** [comment]
Fixed
