### ISSUE TITLE
Ability for donators to customize sounds effects for when they join

### ISSUE THREAD

**Issue by dependants** [WarzoneMC/Warzone#263]
Add a feature for the donators to select their own join sound rather than the plain villager grunt. This can either be unlocked for free or bought for a small price from the shop.

**Comment by scorpion808** [comment]
Maybe if it was free, it can be unlocked by leveling up in-game

**Comment by dependants** [comment]
Yeah, that would be nice. I might make an issue suggesting some level perks, I'll leave it to you if you would like to request it. DM me on Discord - dependants#2228

**Comment by Trophonix** [comment]
Good idea. It could be like /tags but for sounds.
