### ISSUE TITLE
Allow players to use /teleport when spectating

### ISSUE THREAD

**Issue by Palmidence** [WarzoneMC/Warzone#269]
Makes it practical to catch cheaters.

**Comment by BennyDoesTheStuff** [comment]
It could be a custom /tp command. This way, you can prevent players that are in game from teleporting to others.

**Comment by LewisP2018** [comment]
That would be good.

**Comment by lukechatton** [comment]
I don’t think it should be a custom command. /tp is the most user friendly way we could go.

**Comment by Thrasilias** [comment]
This was added recently  ^
https://github.com/WarzoneMC/Warzone/commit/5b35bad1eec4f76fa6e9884c14a9789e4c5ac3d4
