### ISSUE TITLE
Kill streaks

### ISSUE THREAD

**Issue by scorpion808** [WarzoneMC/Warzone#28]
Add a kill streak going around the lines off this
"(Player name) has a kill streak of (5,10,20,30.....)!"
Also make it so that if someone kills a person with a kill streak it would say in chat
"(Killers name) has destroyed (player name)'s kill streak!"

**Comment by spo0p** [comment]
Im legit working on this right now

**Comment by Kronchical** [comment]
Yea, and maybe a /stats too

**Comment by HazryG** [comment]
/stats Didn't work in original warzone, so it would be cool @Kronchical. I'd like to see Kill streaks back because a lot of the players played in games to challenge themselves to get the highest kill streak possible, and it made the game a lot more fun.

**Comment by TheRealPear** [comment]
Bring this back.

**Comment by Bearinx** [comment]
Make it so we can get more xp for the higher we get our kill streaks

**Comment by Palmidence** [comment]
This has been added.

**Comment by MatrixTunnel** [comment]
Added
