### ISSUE TITLE
Void Instadeath

### ISSUE THREAD

**Issue by ghost** [WarzoneMC/Warzone#284]
you fall into the void. you dont have to wait 30 seconds to die. you just die instantly

*This issue was submitted through our issue submission tool.*

**Comment by LewisP2018** [comment]
I would like this to be added.

**Comment by Impuslive** [comment]
I don't want this, as I would prefer it to take time for the other team to respawn. Otherwhise, you would never be able to push to their spawn.

**Comment by dependants** [comment]
It'd be a cool feature if you would die instantly from the void, but you have to wait three seconds prior to respawning.

**Comment by BennyDoesTheStuff** [comment]
Alongside a respawn timer (#83), this could be quite a cool feature to be added to Warzone. Of course, a way to disable/enable this in the JSON would probably need to be added as well just in case.

**Comment by BennyDoesTheStuff** [comment]
#549
