### ISSUE TITLE
Error when breaking wool

### ISSUE THREAD

**Issue by ghost** [WarzoneMC/Warzone#288]
On Avalanche Mini you get an error message when breaking the bottom two roles of wool from the opposite team, you're still able to break it but you keep getting the message "You are not allowed to modify terrain here." This has been a big issue with defending too because you can't place any blocks around the first two layers of wool.

*This issue was submitted through our issue submission tool.*

**Comment by TheRealPear** [comment]
This is also a issue on several other maps such as Ring Race, etc

**Comment by BennyDoesTheStuff** [comment]
This is not an error with TGM.

**Comment by Trophonix** [comment]
This should be on https://github.com/WarzoneMC/Maps, it's a region issue.
