### ISSUE TITLE
Bow cooldown

### ISSUE THREAD

**Issue by FactoDoesStuff** [WarzoneMC/Warzone#29]
Maybe add a bow cooldown to prevent major bow spam on TeamGG?

**Comment by Kronchical** [comment]
I think your on to something Facto, I hate getting bow spammed and I never can build any bridges

+1 Facto

**Comment by TheRealPear** [comment]
No.

**Comment by tjhubz** [comment]
We try to keep pvp on warzone as simple as possible.
