### ISSUE TITLE
Add /report command

### ISSUE THREAD

**Issue by dependants** [WarzoneMC/Warzone#292]
Executing the command properly will successfully submit a report to all staff members currently online, if there are no Moderators to assist with the request then a message will be redirected back the reporter with the explanation on how to report the player using Discord.

Of course, you can message staff members about a cheater problem, but I think that a /report command would be much for suitable for keeping players from spamming a staff members DMs, or spamming in chat about somebody using a blacklisted modification.

**Comment by JapaneseSquid** [comment]
Yeah they used to have this on Avicus too. You can also do /reports -p [playername] to see a report history for a certain player (staff only) or do /reports to show recent reports

**Comment by Draem** [comment]
cool stuff
