### ISSUE TITLE
Suggestion: Give retired people free "choose team" permissions

### ISSUE THREAD

**Issue by AtditC** [WarzoneMC/Warzone#293]
As a "thank you" for their service as staff.

**Comment by JapaneseSquid** [comment]
Yeah, call it “Retired” or “Alumni” or something

**Comment by BennyDoesTheStuff** [comment]
As nice of a suggestion this is, this isn't directly related to TGM. As long as you have TGM connected to an API you can add as many ranks and permissions to those ranks without needing to edit the code.
