### ISSUE TITLE
Publish a command to disable or enable team chat and staff chat

### ISSUE THREAD

**Issue by dependants** [WarzoneMC/Warzone#304]
This command would be useful because you would be able to communicate with the staff team or your matchmaking team without the usage of the original aliases behind your message

Entering the original command that is used for talking in your specific chats without entering a piece of text after that would toggle the feature to speak in your chat without using the alias.

I'd like to credit PandaChan for a portion of this idea.

**Comment by DevGapple** [comment]
Yea I remember several conversations about this. Something like /tchat, /achat, /schat. Or maybe /chat t(a,s) like hypixel's.
