### ISSUE TITLE
Desert Country - Redstone Glitch

### ISSUE THREAD

**Issue by BlueMonkey12** [WarzoneMC/Warzone#306]
On the map 'Desert Country' there's a glitch with the redstone. In front of the Wool rooms there are pieces of redstone which are supposed to act as a barrier to stop the opposing team from getting inside. The redstone barrier doesn't work so when you're getting chased by multiple enemies and you go inside the wool room they can easily get in and kill you. Please fix this issue, it'd be appreciated.

**Comment by BennyDoesTheStuff** [comment]
This is something that would be posted in the Maps repo.
