### ISSUE TITLE
/discord and /forums

### ISSUE THREAD

**Issue by PundaChen** [WarzoneMC/Warzone#318]
Fix/add /discord and /forums, since both don't work at the moment and many users want the Discord link.

**Comment by Crnsxx** [comment]
we can change this to something like `/link`
so it gives all the links
sample
Forums
Discord
etc

**Comment by PundaChen** [comment]
That would be nice, add the twitter then too.

**Comment by Crnsxx** [comment]
Added it :)

**Comment by BennyDoesTheStuff** [comment]
This shouldnt be made here though, the /forums is already made and that's done inside of the "Manager" plugin.
