### ISSUE TITLE
1.13 Support

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [WarzoneMC/Warzone#327]
While using TGM on 1.12.2 and using a plugin like ProtocolSupport works just fine, using TGM on a 1.13 server jar itself breaks and causes the plugin to not load.

**Comment by jellz** [comment]
Can you provide any stack traces?

**Comment by BennyDoesTheStuff** [comment]
Sure - [https://hastebin.com/poqehevifi.bash](https://hastebin.com/poqehevifi.bash)

**Comment by jellz** [comment]
And the only plugin you are using is TGM? Nothing else?

**Comment by BennyDoesTheStuff** [comment]
The only other plugin was ProtocolSupport, but even without that it still spits out the same errors.

**Comment by jellz** [comment]
Thanks.

**Comment by jellz** [comment]
What Spigot version are you using?

**Comment by jellz** [comment]
Nevermind, your stack trace looks to be from 1.13-R1.

**Comment by Thrasilias** [comment]
@jellz You need PaperSpigot (Paper [1.13])

**Comment by BennyDoesTheStuff** [comment]
#442
