### ISSUE TITLE
/alts command for Staff (Mods and lower)

### ISSUE THREAD

**Issue by TheBestGameeer** [WarzoneMC/Warzone#341]
Previously, all staff members had access to the /lookup command. This command showed UUID, Name, Last online times, First join time, Last IP, and other IPs connected to a player/user. It was useful to check for ban evasion or mute evasion, but after an incident with leaking IPs, the command was left for SrMods+.

The idea here is to add a new command that only shows connected accounts or alts of a user without showing the IP. An example could be /alts. The /lookup command can be left for SrMods+, as the rest of the data is not very needed when checking for ban/mute evasion. If an /alts command was added, it would help staff combat ban/mute evasion faster and more efficiently.

Here is an example:

<MOD TheBestGamer> /alts TheBestGamer

Connected accounts:
- TheBestGamer
- TheWorstGamer

**Comment by TheBestGameeer** [comment]
Should also add that, to further protect the privacy of users and preventing IP leaks, to remove the "Punished IP" that pulls up when doing /p (user)

**Comment by Trophonix** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [/alts command for staff to check a player's alts](https://trello.com/c/fbKy9V9A/10-alts-command-for-staff-to-check-a-players-alts)
