### ISSUE TITLE
Rename Warzone repo to TGM

### ISSUE THREAD

**Issue by danielgulic** [WarzoneMC/Warzone#357]
I believe this repo should be renamed to TGM and all occurrences of "Warzone" in the README should be replaced with "TGM."

## Why?
Warzone is the brand/business name. The name of the plugin's developer and main user. The plugin itself is called TGM (Team Game Manager?). By calling the repo Warzone but the plugin TGM, you are creating confusion and decentralization. Therefore, this repository should be called TGM.

**Comment by Trophonix** [comment]
The repo also contains Warzone's API which has stuff that's kinda specific to us already.

**Comment by jellz** [comment]
This happened

**Comment by benrobson** [comment]
Would this mean that the Warzone API be rebranded to TGM api?
I also assume warzone-stats isn't associated with TGM/Warzone as it's not in the org?

**Comment by jellz** [comment]
I think for consistency it would be TGM API, yeah, but not sure if that will happen. I commented on this issue today, but this change was actually made a while ago (back in October 2019).

Warzone Stats is technically an unofficial bot so the code isn't in the Warzone org
