### ISSUE TITLE
Check if CommandSender is a player, or don't cast it to Player at all

### ISSUE THREAD

**Issue by danielgulic** [WarzoneMC/Warzone#358]
The stats command errors if you use the console to send the command. I haven't checked if it needs to be casted to Player but if it does, please implement a check.

![Error](https://i.imgur.com/Pbd8AHk.png)

**Comment by Trophonix** [comment]
Fixed in https://github.com/WarzoneMC/Warzone/commit/05d3c8d21b215cc4588a2fbcea13e49f2b8b7836
