### ISSUE TITLE
Extra curly brace

### ISSUE THREAD

**Issue by ThatOneTqnk** [WarzoneMC/Warzone#359]
Just an extra curly brace
https://github.com/WarzoneMC/Warzone/blob/9489ecaf630bbc361a38e957af4f6ba6f5471be6/TGM/src/main/java/network/warzone/tgm/modules/filter/FilterManagerModule.java#L119

**Comment by Trophonix** [comment]
There isn't a missing brace. The problem was they named the class ShearFilterType inside the file UseShearFilterType. 

@Palmidence please write code in an IDE.. or get a better IDE if you already do lol

**Comment by ThatOneTqnk** [comment]
ye it was fixed in https://github.com/WarzoneMC/Warzone/commit/098a3e36eee3466f7c7ba0cedcbf443db42dbbd3
