### ISSUE TITLE
Spectator spawn bug

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [WarzoneMC/Warzone#375]
For some reason, on random maps, it teleports the spectators to the world's spawn when it's cycled to that map instead of the spectator spawn defined in the JSON.

**Comment by BennyDoesTheStuff** [comment]
Sidenote: If a player joins the server after the game already started, it teleports them to the correct spawn. Seems as if it's only an issue when teleporting players initially on world load.

**Comment by danielgulic** [comment]
I tested this on my local server with 50+ maps and in all of them I was teleported to the correct spectator spawnpoint

Cannot reproduce.
