### ISSUE TITLE
TGM

### ISSUE THREAD

**Issue by TRose2000** [WarzoneMC/Warzone#379]
- Add more support for 1.13 [https://github.com/WarzoneMC/Warzone/issues/327]
        - Global code cleanup (if needed)
        - Add more Deathmessages (Bold when the player is involved)
        - AFK Timer needs to be fixed
        - Add DTC (Destroy The Core)
        - Fix Spectator issues {stop interacting with doors, trapdoors, levers, chests, buttons,}
        - Change XP Bar to something like a custom actionbar that shows ur level, instead of using the XP system

**Comment by BennyDoesTheStuff** [comment]
Issues already exist for these.
