### ISSUE TITLE
whats this for

### ISSUE THREAD

**Issue by TRose2000** [WarzoneMC/Warzone#439]
for what is this part in the config
`server:
  name: "Warzone"
  id: "warzone"`

**Comment by ThatOneTqnk** [comment]
https://github.com/WarzoneMC/Warzone/blob/1bd79dcd228a90bebe85eb3f064b07805bed2d13/WarzoneAPI/src/main/java/network/warzone/warzoneapi/models/Heartbeat.java#L16

**Comment by TRose2000** [comment]
ik that but is it active like getting used or is it never finished?

**Comment by ThatOneTqnk** [comment]
https://github.com/WarzoneMC/Warzone/blob/1bd79dcd228a90bebe85eb3f064b07805bed2d13/WarzoneAPI/src/main/java/network/warzone/warzoneapi/client/http/HttpClient.java#L58-L70

https://github.com/WarzoneMC/api/blob/b650b9a8907e3c4ce06cbd461ecab3c3928dcd95/routes/minecraft/servers.js#L66-L78

https://github.com/WarzoneMC/api/blob/b650b9a8907e3c4ce06cbd461ecab3c3928dcd95/routes/minecraft/servers.js#L80-L95

**Comment by TRose2000** [comment]
ah i see thanks anyways <3
