### ISSUE TITLE
TNT breaks region logic

### ISSUE THREAD

**Issue by Palmidence** [WarzoneMC/Warzone#44]
When using TNT on either a monument on DTW or a protected region, it breaks. I'd assume this carries on to other regions as well.

- On a region that's an objective, once it interacts with TNT, becomes void. Any further player interaction with the monument is not tracked, and it is stuck at the percentage it is until a mod ends. However, before TNT interacts with the region, it's fine.

- On a protected region, such as a spawn, if TNT lands in it then it destroys the region (intended behavior would be that its protected).

This is an issue on Warlock and Ascension, as both contain traces of TNT.

**Comment by BennyDoesTheStuff** [comment]
That's true ^
Especially with Ascension which literally has 4 double chest of tnt on each side of the map, it gets very crazy and messes up the map from being winnable.

**Comment by tjhubz** [comment]
New region flag for tnt! :D
