### ISSUE TITLE
The /end command is broken

### ISSUE THREAD

**Issue by Hxnr** [WarzoneMC/Warzone#448]
/end yields an error when being used (even as an op).

**Comment by BennyDoesTheStuff** [comment]
What error are you getting? Are you using the command while the game is running?

**Comment by Hxnr** [comment]
That could be it. What I remember is it gave me something similar to "internal error", but it's probably best to test it.

**Comment by Aerhh** [comment]
Could you grab the error from the console window and paste it here? I can't reproduce this.
