### ISSUE TITLE
Infected: Humans can die to the void without becoming infected

### ISSUE THREAD

**Issue by Draem** [WarzoneMC/Warzone#459]
Currently, the onDamage event in the InfectedModule relies on the `EntityDamageByEntity` event, which prevents the method from running if someone falls into the void, or dies from another cause.  ![Use of EntityDamageByEntity event](https://i.imgur.com/hVM1Sy6.png)

There are also an if statements that prevent anything from running if the damager isn't an entity, which will have to be removed. ![If statement](https://i.imgur.com/m5JEnjN.png)

**Comment by BennyDoesTheStuff** [comment]
Duplicate of #455 but this is way more detailed

**Comment by Draem** [comment]
Fixed.
