### ISSUE TITLE
Remember place in rotation after server is shutdown

### ISSUE THREAD

**Issue by AttendantFox** [WarzoneMC/Warzone#467]
When the server is closed/shutdown, remember the current place in the rotation so all the maps can be played on instead of the same 10 or so

**Comment by Draem** [comment]
@ThatOneTqnk @jellz both are official warzone developers they can take care of it!

**Comment by Owehttamy** [comment]
Wouldn't it be possible to just have a climbing integer every time the next map loads, so when the server restarts it goes to the map next in the rotation?
For example, if the rotation is at 5 the integer is set to 6, then the server asks for the value of the integer when starting up to set to that map?
The only "difficulty" of implementing this is just having the server set to the map next in the rotation, which shouldn't be that difficult to setup.

**Comment by ThatOneTqnk** [comment]
Sure, but the integer cannot be stored in memory since it has to persist in between restarts.
