### ISSUE TITLE
1.8 users cannot see name colors in tab or in their name

### ISSUE THREAD

**Issue by Hxnr** [WarzoneMC/Warzone#472]
When using version 1.8, you cannot see player's colored names in tab or when you are next to them. This is very unhelpful as you need to see what team they are on.

**Comment by TBG1000** [comment]
This also happens in 1.12.2 and 1.13.2

**Comment by Hxnr** [comment]
@ThatOneTqnk @jorgeberrex draem has looked into this and is unable to find the fix. This is a pretty important issue that should be fixed before the tournament on Saturday as most users are on 1.8. Are any of you able to take a look?

**Comment by Draem** [comment]
tryna sell me out

**Comment by Owehttamy** [comment]
If we're unable to fix the visibility of players' colors then we could possibly give them colored prefixes or prefixes with the first letter of their teams' color.

**Comment by Hxnr** [comment]
This issue has been fixed by Jorge and draem on versions 1.8 and 1.14.
