### ISSUE TITLE
Spectator blocking

### ISSUE THREAD

**Issue by Draem** [WarzoneMC/Warzone#479]
As a spectator you can fly in the way of people bridging or just placing blocks and prevent them from placing blocks.

_Tested :)_

**Comment by Owehttamy** [comment]
Why does this suddenly not work?

**Comment by Owehttamy** [comment]
Draem's code reverted. Is there reasoning for it or what happened?

**Comment by BennyDoesTheStuff** [comment]
That PR didn’t fix the issue, it’s currently an issue only on Spigot and he was testing his changes using PaperSpigot which has fixed this

**Comment by Owehttamy** [comment]
Ah okay thanks for clarity

**Comment by Aerhh** [comment]
Yeah it didn't fix the issue but that's because Minehut apparently uses Spigot while the README says Paper, so I followed the README to set up a local env.

**Comment by jorgeberrex** [comment]
Issue is fixed by PaperSpigot since it's now a dependency.
