### ISSUE TITLE
[SUGGESTION] Stats interface for players + Levels

### ISSUE THREAD

**Issue by Sitars** [WarzoneMC/Warzone#48]
I think that /stats should be accessed by all players. I know that you can just go to the website, but what if you are playing and can't search for the player? /stats would be an easy way to do just that. Along with that, I think that the old feature of leveling up should be added alongside this. Just my two cents.

~ Sitars

**Comment by MatrixTunnel** [comment]
We have plans for both of these features! Updates are coming soon so stay tuned ;)

**Comment by TheRealPear** [comment]
Can't wait!

**Comment by Sitars** [comment]
That is awesome!
