### ISSUE TITLE
Ability to define a command to be run when match starts

### ISSUE THREAD

**Issue by jellz** [WarzoneMC/Warzone#487]
In the map.json of a map, the map creator should be able to define a command to be run when the match starts. This could be useful for various things, one being to activate a chain of command blocks with `/setblock x y z redstone_block`.

**Comment by CrazyisCreeps** [comment]
Maybe to make it even more useful, allow for the activitivation to be triggered at any specified time in the json? Say you needed something to happen after 1m/30s/etc
