### ISSUE TITLE
Spectators do not become visible after game end

### ISSUE THREAD

**Issue by Draem** [WarzoneMC/Warzone#491]
![](https://i.imgur.com/OMf0C9V.png)

I cannot see two of the spectators because they did not join last game. 
Most likely caused by the fact that spectators don't become visible again after the game ends?
Just a theory

**Comment by AtditC** [comment]
Under no circumstances ever make spectators visible to players after the game has ended. This would make spectating suspects, especially active Warzonians who know all staff members, a lot harder. They would immediately know they have been spectated/will be spectated and thus stop with whatever they did prior. I'm just mentioning this here in case someone wants to resolve this issue this way. I highly discourage using this way.

**Comment by JapaneseSquid** [comment]
Agreed with atdit

**Comment by Draem** [comment]
Let me correct myself to what I meant- they'll become visible after the match unloads and the next match is loading. Spectators should be able to see other spectators
