### ISSUE TITLE
Timed Events

### ISSUE THREAD

**Issue by SirGoldman-git** [WarzoneMC/Warzone#522]
**Request:**
Able to use the `map.json` to run commands as console every set amount of time.

**Reason:**
This would open the door for many new possibilities, like care packages or mob spawning.

**Comment by MrScopes** [comment]
i can see this being pretty useful

**Comment by BennyDoesTheStuff** [comment]
Can be possible by using something like this in the JSON:

```JSON
	"time": {
		"broadcasts": [
			{
				"interval": 10,
				"repeat": true,
				"commands": [
					"give @a arrow 1"
				]
			}
		]
	},
```
