### ISSUE TITLE
Wool Explosion Issue

### ISSUE THREAD

**Issue by SirGoldman-git** [WarzoneMC/Warzone#524]
**Problem:**
When using the DTM gamemode you can use TNT to break wool so the other users cant win the game. This can be done with withers as well if it's summoned near the wool.

**Request:**
Deny wool explosion block damage in protected monument areas.

**Comment by jellz** [comment]
Or, we could make explosions count toward the monument health

**Comment by SirGoldman-git** [comment]
I was unaware, that works better!

**Comment by MrScopes** [comment]
there's that one map with all the tnt though, if tnt counted towards the wool people could win in seconds

**Comment by BennyDoesTheStuff** [comment]
```
{
		"type": "block-explode", "evaluate": "deny", "teams": ["blue", "red"],
		"regions": ["blue-wool", "red-wool", "blue-spawn-protection", "red-spawn-protection"]
}
```

You could take advantage of something like this in the JSON. This way, it will prevent both teams from breaking the wool using something like TNT.
