### ISSUE TITLE
Use config for messages

### ISSUE THREAD

**Issue by MrScopes** [WarzoneMC/Warzone#525]
instead of an entire new repository for broadcasts, why not just put them in the config file?

**Comment by BennyDoesTheStuff** [comment]
?

**Comment by MrScopes** [comment]
> ?

meant the broadcasts

**Comment by BennyDoesTheStuff** [comment]
All the broadcasts are already in a config. We just have a repo setup and the config file is auto updated to whatever the repo is setup.
