### ISSUE TITLE
Stats Command

### ISSUE THREAD

**Issue by Bearinx** [WarzoneMC/Warzone#53]
Add a command so if you are in a game you can do a command like /stats and it will show in chat a chart with your kills deaths and the kill to death ratio. This would be better than having to go to the team.gg website and looking at the end game results (Also because that is broken) 

~ Bearinx

**Comment by jackstebbing** [comment]
I'd love this to be added!

**Comment by Sitars** [comment]
MatrixTunnel told me they are adding it.

**Comment by tjhubz** [comment]
#48
