### ISSUE TITLE
Naval Conquest Removal

### ISSUE THREAD

**Issue by FieryAU** [WarzoneMC/Warzone#54]
After playing Naval Conquest around 3 times, we have realised that there are some flaws in the system. Players on a 1.12 client can use a boat without any problem, yet players on 1.8 client will unshift from the boat and end up back where they boarded it.

Yes, you can simply bridge to their ship, like I did. But 1.12 players get an advantage.

**Comment by tjhubz** [comment]
Not an issue with the map, rather the client. 1.8 support will be removed.
