### ISSUE TITLE
Respawning at match end

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [WarzoneMC/Warzone#551]
**Describe the bug**
If you're on the respawn screen when the match ends, it doesn't let you move or see anything until the match cycles

**To Reproduce**
Steps to reproduce the bug:
1. Die while in the game
2. End the game before the respawn timer is up

**Expected behavior**
It should allow you to fly around and get rid of your blindness when the match ends

**Server Software (Spigot/PaperSpigot):**
Spigot

**Comment by jorgeberrex** [comment]
Resolved in https://github.com/WarzoneMC/Warzone/commit/a2cea84d0e988441d30352778ff48ecbd888295a.
