### ISSUE TITLE
Invisibility bug

### ISSUE THREAD

**Issue by residesJack** [WarzoneMC/Warzone#556]
**Describe the bug**
At times, players are turned invisible, but are suddenly reappearing moments later or even after 20 seconds.

**To Reproduce**
Steps to reproduce the bug:
1. Join a team.
2. Navigate to a player 
3. Watch if they become invisible. 

**Expected behavior**
Players do not go invisible.

**Additional context**
This can drastically influence the result of a match, including somebody's personal statistics. This clearly needs to be fixed.

**Comment by AtditC** [comment]
This also happened a lot of times to me with random players. I always use 1.8.9. It happens randomly and when it happens, you can just press F3 + A to reload the chunks and the player becomes visible again. Also, if this is any useful information, you can still see the particles when the visible player sprints around, and you can even shoot them, and probably also hit them with the sword (although I'm not too sure about hitting them with the sword.)

**Comment by Owehttamy** [comment]
You can attack them normally, it's just visibility is the issue. Also it'd be nice if we can find the issue because Badlion Client doesn't have F3 keybinds :/

**Comment by ThatOneTqnk** [comment]
This seems to be happening due to the map and not the plugin. Nevertheless, maps are being updated and it appears that the issue is not present in the updated maps.
