### ISSUE TITLE
Some Kills not Announced in Chat or no Death Sound

### ISSUE THREAD

**Issue by Owehttamy** [WarzoneMC/Warzone#558]
Occasionally players will die in close combat and they would begin the respawn sequence, but the kill isn't announced nor is the death sound effect played.

This may also mean that stats aren't affected due to this, but I'm not completely sure.

The steps to recreate this aren't really known, and is most likely based on lag and the hit registration bug from #557.

**Comment by ThatOneTqnk** [comment]
Issue has been resolved.
