### ISSUE TITLE
Disable crafting of items

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [WarzoneMC/Warzone#565]
**Describe the feature you'd like**
The ability to disable crafting certain items.

**Usefulness of the feature**
Could prevent crafting of items such as shears in maps that have iron blocks.

**Additional context**
This could probably be done either:
- By default disabling crafting for the item remove module
- Allow map makers to specifically define what items cannot be crafted
- Allow map makers to define if they want items in the item remove to not be craftable (default would be to allow).

**Comment by Draem** [comment]
Added in https://github.com/WarzoneMC/Warzone/commit/ffc897a7ed7b2a3169aaee13a74a609689d6403e
