### ISSUE TITLE
Multiple coordinates in a region.

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [WarzoneMC/Warzone#566]
**Describe the feature you'd like**
The ability to insert multiple coordinates into a region.

**Usefulness of the feature**
It could be useful for mapmakers if they want to select multiple areas of a map to all be in 1 region or if a map maker wants only a few specific blocks in a region.

**Comment by jorgeberrex** [comment]
Added in https://github.com/WarzoneMC/Warzone/commit/7801e23ba0c2c8a5488dc249b816f5fbbce66812
