### ISSUE TITLE
One shot matches do not end if player is banned

### ISSUE THREAD

**Issue by residesJack** [WarzoneMC/Warzone#570]
**Describe the bug**
Reported by Clijmart, banning a player who is the last participant on their team does not end the game.

**Client version**
1.8.9

**To Reproduce**
Steps to reproduce the bug:
1. Ban the last player on their respective team on the map 'No Return'.

**Expected behavior**
Game automatically wins, registering the win to the opposing team.

**Server Software (Spigot/PaperSpigot):**
PaperSpigot

**Comment by Owehttamy** [comment]
I also believe the same happens if the last player on a certain team changes to spectator or if they leave the server in general.

**Comment by BennyDoesTheStuff** [comment]
This goes the same for any other gamemodes like Blitzc, TDM, etc. I’m not sure what’s the best way to go about this as people do use TGM to test maps and we don’t want the game to suddenly end when they switch to Spectators or when they only have 1 account testing.

**Comment by jorgeberrex** [comment]
Hopefully this is resolved by https://github.com/WarzoneMC/Warzone/commit/d62708917b696d00b48bd0c68c0624c8aea1813e. Will reopen if the issue continues after this is live in production.
