### ISSUE TITLE
TP HACKS

### ISSUE THREAD

**Issue by Draem** [WarzoneMC/Warzone#572]
**Describe the bug**
You can craft a compass on Midnight Train, and some other maps, and then use them to teleport.

**Client version**
1.8.9

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Midnight Train.'
2.  Go to the mine and get 4 iron and a redstone.
3. Craft a compass.
4. ???
5. Profit.

**Expected behavior**
You can't teleport.

**Screenshots**

**Server Software (Spigot/PaperSpigot):**
PaperSpigot

**Additional context**
Very epic to teleport to other side before bridges are made!

**Comment by jellz** [comment]
Can reproduce

**Comment by jellz** [comment]
NB: This is only possible with WorldEdit installed and players have the permission to use the teleport compass

**Comment by Owehttamy** [comment]
#565 also possible "important" tag?

**Comment by ThatOneTqnk** [comment]
this is already resolved

**Comment by Draem** [comment]
??? Profit
