### ISSUE TITLE
draem doesn't have nick perms

### ISSUE THREAD

**Issue by Draem** [WarzoneMC/Warzone#581]
**Describe the bug**
draem doesn't have nick perms :(

**Client version**
1.8.9

**To Reproduce**
Steps to reproduce the bug:
1. draem tries to use /nick
2. It doesn't work

**Expected behavior**
draem can use /nick

**Screenshots**
![](https://i.imgur.com/31h28DO.png)

**Server Software (Spigot/PaperSpigot):**
PaperSpigot

**Additional context**
No nick perms :(

**Comment by BennyDoesTheStuff** [comment]
Please don’t make joke issues.
