### ISSUE TITLE
JSON enchantments don't work

### ISSUE THREAD

**Issue by AtditC** [WarzoneMC/Warzone#582]
**Describe the bug**
Items which are supposed to be enchanted don't get enchanted ingame. Example: Bow on Quintus doesn't have Infinity on it. Items which can be found in chests on the map are enchanted just fine.

**Client version**
1.8.9

**To Reproduce**
Steps to reproduce the bug:
1. Play a map which enchanted items in the loadout
2. Find out the enchanted items aren't enchanted

**Expected behavior**
The items should be enchanted

**Screenshots**
no

**Server Software (Spigot/PaperSpigot):**
PaperSpigot

**Additional context**
Chestplates still can be enchanted with blast protection, so armor might not be affected, only items, or certain enchantments.

**Comment by ThatOneTqnk** [comment]
Enchantment parsing was changed (e1eaf2fd55dd7b7a2f336e185d6c4712870bb31e)
