### ISSUE TITLE
Scoreboard strikethrough still broken lol

### ISSUE THREAD

**Issue by Owehttamy** [WarzoneMC/Warzone#585]
**Describe the bug**
#583 but with DTW

**Client version**
1.8.9 but would very likely happen in other versions too

**To Reproduce**
Steps to reproduce the bug:
1. Break wool completely
2. Roll a dice
3. Look at scoreboard

**Expected behavior**
Strikethrough text has the same color throughout

**Screenshots**
![proofthatimnotcrazyandthatitsstillbroken](https://user-images.githubusercontent.com/47429979/66538855-c41d9d00-eaeb-11e9-86ae-90190bcdf57f.PNG)
heheheh you thought I was crazy didn't you Jorge

**Server Software (Spigot/PaperSpigot):**
PaperSpigot

**Additional context**
nice
also maybe this time you link the commit to the issue so it doesn't just look like it's closed because I was lying or something

**Comment by jorgeberrex** [comment]
This issue has already been fixed but it's not yet live in production
~~_so I do think you are crazy_~~
