### ISSUE TITLE
Spectators flicker when joining a team and playing

### ISSUE THREAD

**Issue by Owehttamy** [WarzoneMC/Warzone#586]
**Describe the bug**
Whenever you join the game, all of the other players you saw create a duplicate that flickers in the spot where you last saw them.

**Client version**
1.8.9
Other people said it was happening when they weren't playing in 1.8.9

**To Reproduce**
Steps to reproduce the bug:
1. Look at other players before joining
2. Join
3. Badda bing badda boom another bug found

**Expected behavior**
People don't get seizures from Warzone

**Screenshots**
![anotherbugbaddabingbaddaboom](https://user-images.githubusercontent.com/47429979/66539097-938a3300-eaec-11e9-9692-6d74ce2d24d7.PNG)
Obviously you don't see flickering here but I think you can trust me on that one

**Server Software (Spigot/PaperSpigot):**
PaperSpigot

**Additional context**
Why is there so much fuss with hiding spectators dammit

**Comment by jorgeberrex** [comment]
Cannot reproduce, unclear instructions, likely to be a 1.8.9 ProtocolSupport issue
