### ISSUE TITLE
Add /gametime command

### ISSUE THREAD

**Issue by Owehttamy** [WarzoneMC/Warzone#590]
**Describe the feature you'd like**
Whenever the game starts, a counter is increased by an interval of either seconds or minutes.
Then, whenever someone does "/gametime" or "/duration", it displays how long the game has been going for.

**Usefulness of the feature**
Helps gives the players an idea of how much time they've spent on the game

**Additional context**
It could be useful in cases of the "/playtime" command from #279 because the counter from this feature could be used for it once the API is rewritten.
Also could be another statistic of #251

**Comment by Owehttamy** [comment]
It shows the date, not how long the game has been going for or was

**Comment by jorgeberrex** [comment]
> It shows the date, not how long the game has been going for or was

You're either asking for a command that shows you real time which I guess would be useful if you're an owl or you're asking for a command that shows you the time elapsed in the match which is what it already does: 

![time elapsed](https://i.imgur.com/8U4vAeZ.png)

**Comment by Owehttamy** [comment]
![areyousureaboutthat](https://user-images.githubusercontent.com/47429979/66694464-37a0e500-ec79-11e9-86d3-2cf0c4ef73e9.gif)

**Comment by BennyDoesTheStuff** [comment]
That doesn't exist in a plugin, that might be apart of a mod you're using.

**Comment by jorgeberrex** [comment]
![I'm pretty sure](https://media1.tenor.com/images/6e48b81b45dd7ee775165a9e96d5cf25/tenor.gif)

Despite your gif being particularly small, I can tell you your client is overriding the /time command ¯\_(ツ)_/¯
