### ISSUE TITLE
CTW Wool Map

### ISSUE THREAD

**Issue by TBGameeer** [WarzoneMC/Warzone#63]
In the CTW maps, Deepwind and Outback, you can place the wool as you grab it throughout the spawn, middle islands and your own team's spawn.

I believe this feature should be removed and that wool should only be place-able in the correct spot (behind the spawn in Deepwind, at the side of the spawn in Outback) because a player can just grab a stack of wool from the infinitively restocking chests and go placing wool as he goes back to his spawn.

If he dies, and he placed wool in his spawn island, he can just go back and mine it from there to go place it. It is a very easy way to win since you dont have to go back to the wool area/building, which I think breaks the purpose of the game.

**Comment by tjhubz** [comment]
New CTW maps will use spawners instead of chests.

**Comment by TBGameeer** [comment]
How much will the wool spanwers spawn? Will it detect when a player has enough/ x amount of wool? If the spawner continuously spawns wool, you can still place it on your way back to your spawn, which, if you die, allows you to go a close island / location where you placed it and carry it back to the wool placing area.

**Comment by tjhubz** [comment]
You can see how much they spawn on the map "Pipe Palace" currently.

**Comment by tjhubz** [comment]
It reduces the amount of wool significantly.
