### ISSUE TITLE
Add clans with clan pages on website

### ISSUE THREAD

**Issue by jellz** [WarzoneMC/Warzone#74]
You should add in-game clans. Whenever a guild member gets a kill or wins a game, etc, it goes towards the guild points. You can find details about the guild posted by the guild leader, along with their stats on **https://warz.one/c/clanName**.

Maybe in chat, it also shows the clan you're in? I don't know! 🤣

**Comment by FieryAU** [comment]
This would be a great addition in my opinion!

**Comment by Synconix** [comment]
That is a cool idea

**Comment by tjhubz** [comment]
Switching to a different website system, not sure if this feature can be added. Will be brought up with forumsgg.

**Comment by jellz** [comment]
I think this issue should be reopened, but without the website part. The clans would be entirely in-game.

**Comment by jellz** [comment]
This would also be a unique feature. As far as I know, no other PGM/TGM has this.
