### ISSUE TITLE
Add /next command

### ISSUE THREAD

**Issue by tjhubz** [WarzoneMC/Warzone#78]
Allows players to see the next map that will be played.

**Comment by LungedAlex** [comment]
Unless a map is set by force, you can see upcoming maps and the map you're playing on with /rot

**Comment by BennyDoesTheStuff** [comment]
Yes, but if a map is being played that's not in the rotation, you wouldn't know which map is coming up next. Overall it's much easier to just add a /next command to quickly use to view the next map set.

**Comment by tjhubz** [comment]
#140
