### ISSUE TITLE
Void Damage

### ISSUE THREAD

**Issue by Bearinx** [WarzoneMC/Warzone#82]
Make falling into the void an instant death.

**Comment by Palmidence** [comment]
I think @jorgeberrex said it wasn't practical to add.

Keep in mind, void death also acts as a respawn timer. We'd need to edit a lot of maps (Balloons, Warlock, Snowy Wars, etc.) and it also allows for the enemy to be gone for a bit once you kill them so if you're running past their spawn, they don't get to instantly fight you again.
