### ISSUE TITLE
Premium Team Join Mid Game Fix

### ISSUE THREAD

**Issue by Bearinx** [WarzoneMC/Warzone#85]
Premium Players can join the winning team mid game and get the easy win so they can level faster.

**Comment by Bearinx** [comment]
You can fix this by making it so if you join a team mid/end game and they win then they don't get the xp for the win

**Comment by FieryAU** [comment]
Just make a timer, like first one and a half minute you can manually join a team. If the teams are unbalanced, the server will automatically balance the teams with almost the same amount of players on the same time. (like 1 to 3 players difference)

**Comment by MatrixTunnel** [comment]
I actually have a plan that will fix this and the issue of players leaving before losing ;)

**Comment by tjhubz** [comment]
#102
