### ISSUE TITLE
Basic Kits

### ISSUE THREAD

**Issue by Virtualizes** [WarzoneMC/Warzone#89]
The kits have not yet been released yet, but I think that there should be more basic kits than the previous kit system.

I think that the kits shouldn't have super special abilities such as fire, protection, etc. They should be more simple.

Basically, the kits would be similar to this, just something cleaner and unique.

Marksman - Usually apart of base defense - More arrows but weaker gear
Tank - Also usually apart of base defense - Stronger gear
Rusher - Full leather
Midfighter - Full leather with an iron chest plate

(arrow count would have to be nerfed for default)

**Comment by MatrixTunnel** [comment]
Agreed. We're not planning on adding the same kits for each map though. Abilities are going to be added which will allow map creators to make kits the way they want. You could make it with or without abilities depending on what you want the gameplay to feel like

**Comment by FieryAU** [comment]
Sounds great!
