### ISSUE TITLE
Combat Log

### ISSUE THREAD

**Issue by Virtualizes** [WarzoneMC/Warzone#90]
Hello, I have seen many complaints about players leaving the game if they have been knocked into the void or are about to die in combat. In some circumstances, the player might actually have to go right away which might affect this system.

Basically, if a player engages in PvP, they will be on a combat timer. Leaving the game in the period that the timer is running will result in an automatic death and maybe at least one random stat being decreased by 1-3 points.

Combat logging hasn't been a huge problem, but many players have experienced this and are getting quite annoyed.

**Comment by tjhubz** [comment]
Not a huge problem at the moment, we have other stat abuse changes coming soon.
