### ISSUE TITLE
Add a /stats reset command

### ISSUE THREAD

**Issue by Bearinx** [WarzoneMC/Warzone#92]
If one of the players were caught hacking we can /stats reset the banned player also you can make it auto wipe stats on ban (PvP related until movement system fix)

**Comment by Pndq** [comment]
But what if a legit player gets false banned who has fairly earned their stats and gets banned? That would be unfair since they got a stat wipe for not hacking. Example say im pvping and I get false banned. All the stats I wotked for are gone. This also goes for every other player

**Comment by tjhubz** [comment]
This is not needed. If they are banned there is no point to resetting stats.
