### ISSUE TITLE
Void Glitch

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [WarzoneMC/Warzone#94]
People keep getting stuck in the void, meaning staff would have to tp you out of the void or you'll have to relog since not even doing /kill would get them unstuck.

**Comment by Synconix** [comment]
I think this was fixed, or maybe it just has not happened to me in while

**Comment by scorpion808** [comment]
I think I made a temp fix for this bug but I forgot to pull request it.

**Comment by scorpion808** [comment]
I've noticed that you take no fall damage when this happens. Like right before you fall into the void if you fall from like ten blocks and land on the ground, you don't take any damage.

**Comment by BennyDoesTheStuff** [comment]
Haven't noticed this bug happening in months now, assume it was fixed.
