### ISSUE TITLE
Add more Tags

### ISSUE THREAD

**Issue by crewly** [WarzoneMC/Warzone#96]
A lists of Tags that should be added
WAT
LMFAO
DANK
FAN
FREE (basically a free tag)
1337
MONEY (Person who bought every tag)
LAZY

Those are all of my tags suggestions 😉

**Comment by DeternoMC** [comment]
Nah, I don't like the free tag idea- tag was supposed to be a donator only thing, and you're going to see everyone with the free tags.

Also, as a suggestion, I'd like to see some colours in tags! :D

**Comment by tjhubz** [comment]
Some of these may be added in the future.
