### ISSUE TITLE
Idea for Tournaments

### ISSUE THREAD

**Issue by TBGameeer** [WarzoneMC/Warzone#97]
Suggestion for (possible) future tournaments

When guilds become a thing, Warzone should host some tournaments with those guilds. I was thinking in a 10v10 DTW or CTW or any gamemode with 2 guilds. The tournament should have several rounds so if the guild has more than 10 members, everyone has a chance of playing. There could be 10 starting players then 5 new players could come in, etc. This is to keep it cycled and fair.

**Comment by BennyDoesTheStuff** [comment]
ooooooo we actually are hoping to have tournaments like these in the future. Back then in the old warzone, we used to have warzone tournaments hosted qutie often and they were pretty fun tbh.
([https://www.minehut.com/forums/topics/58e050c2bc940e57e69f2928](url))

**Comment by Bearinx** [comment]
Here is a good idea for staff reasons, we could have reuploads of all the maps but make it so the maps all have the JSONs to have team limits set to zero like staff can cycle it to (Rooted t) t = tournament and when it cycles the map is preset to 0 as the team limit.

**Comment by DeternoMC** [comment]
And possibly, could the tournaments not last 1 day and go over a few days? that'd be nice!

**Comment by FieryAU** [comment]
It would also be cool if the winning team gets a prize, such as a custom tag, and possibly a VIP rank or some sort of appreciation.
Second place could get a tag of their choice.

**Comment by tjhubz** [comment]
We plan to integrate clans and tournaments when we can.
